[package]
name = "gluenote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"

[dependencies.gluesql]
version = "0.11"
default-features = true
features = ["index"]
